### ISSUE TITLE
Prebuildify for armv7 musl

### ISSUE THREAD

**Issue by alexojegu** [prebuild/prebuildify-cross#17]
Would an image for armv7 musl be possible? It could be based on [dockcross/linux-armv7l-musl](https://github.com/dockcross/dockcross#dockcrosslinux-armv7l-musl) (for use with Alpine armv7 which if I'm not mistaken is really armv7l).

**Comment by vweevers** [comment]
PR is welcome over at https://github.com/prebuild/docker-images

**Comment by vweevers** [comment]
Image has been published. Thanks!
