### ISSUE TITLE
V4 not released on npm

### ISSUE THREAD

**Issue by Justkant** [prebuild/prebuildify-cross#8]
You can check this [here](https://www.npmjs.com/package/prebuildify-cross)

For the moment I use the github notation inside my package.json:
```
    "prebuildify-cross": "github:prebuild/prebuildify-cross#v4.0.0"
```

**Comment by vweevers** [comment]
Blocked by https://github.com/prebuild/prebuildify-cross/pull/7#issuecomment-554653443

**Comment by Justkant** [comment]
Yep just saw the comment :+1:

**Comment by vweevers** [comment]
Friendly ping @ahdinosaur as more folks are starting to use `prebuildify-cross`. Could you run `npm owner add vweevers prebuildify-cross`? Thanks!

**Comment by Justkant** [comment]
I found a better/easier way to create prebuilds for multiple platforms (had some issues with prebuildify-cross).
I'm going to document everything soon, but I first need to see where this could fit.

**Comment by ahdinosaur** [comment]
oops i'm so sorry, added you @vweevers!

**Comment by vweevers** [comment]
Thank you! Published.
